### ISSUE TITLE
找不到org.xjcraft

### ISSUE THREAD

**Issue by enshulv** [XJcraft/XJBalance#2]
Could not resolve dependencies for project com.zjyl1994.minecraftplugin:MultiCurrency:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.xjcraft:SimpleSpigot:jar:LATEST: Failed to read artifact descriptor for org.xjcraft:SimpleSpigot:jar:LATEST: Failed to resolve version for org.xjcraft:SimpleSpigot:jar:LATEST: Could not find metadata org.xjcraft:SimpleSpigot/maven-metadata.xml in local 
打包的时候会提示错误，请问这个有提供吗？

**Comment by reezhu** [comment]
这个由于保密协议的关系，不能开源哈，是配置工具，不影响插件的功能

**Comment by enshulv** [comment]
好的，谢谢
